### ISSUE TITLE
#RLV Folders not showing on hypergrid

### ISSUE THREAD

**Issue by typhartez** [lickx/oscollar#60]
I tried to access the #RLV folders from my alter ego on another grid, and nothing shows.

- Wearer: on foreign grid
- Trusted: on own grid, access to most collar functions (leash, poses, RLV restrictions)
- #RLV Folders menu never shows

I have not investigated in the code yet

**Comment by lickx** [comment]
This is not a OsCollar bug but a hypergrid/viewer problem. #RLV access only works if your homegrid doesn't enable the 'My suitcase' "feature". Another reason why hypergrid is just a very bad idea until it becomes more than a proof-of-concept (it should have never been included in this state in OpenSim).

Try it out, make an OsGrid avi, populate #RLV and you'll see then it works because OsGrid has the suitcase disabled.

On another note; making an #RLV subtree in My Suitcase will not work, the viewers are not intelligent enough to prefer that folder over the regular #RLV folder if My Suitcase exists.

**Comment by typhartez** [comment]
Yes, I somehow thought about that. And for a #RLV folder in My Suitcase, it wouldn't be a solution either. Duplicating links would be a pain, and maintaiging the two synchronized would be even more.

I hoped there was just a limitation in the collar code, but you confirmed not.
